newnovel/urls.py
from django.conf.urls import include, url, handler404, handler500
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


handler404 = "novel.views.page_not_found"
handler500 = "novel.views.page_error"

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('novel.urls', namespace='novel', app_name='novel')),
    url(r'^usercenter/', include('usercenter.urls', namespace='usercenter', app_name='usercenter')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

novel/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'novel'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', views.search, name='search'),
    url(r'^book/(?P<book_id>[0-9]+)/$', views.book_index, name='book'),
    url(r'^book/(?P<book_id>[0-9]+)/(?P<index>[0-9]+)/$',
        views.chapter, name='chapter'),
    url(r'^update/(?P<book_id>[0-9]+)/$', views.update, name='update'),
    url(r'^download/(?P<book_id>[0-9]+)/$', views.download, name='download'),
    url(r'^feedback/', views.feedback, name='feedback'),
]

novel/models.py
# coding=utf-8

from django.db import models
from django.conf import settings

# Create your models here.


class Config(models.Model):
    # 站点源信息
    site_short_name = models.CharField(
        max_length=20, verbose_name='ID', unique=True)
    site_desc = models.CharField(max_length=50, verbose_name='站点源')
    site_url = models.CharField(max_length=200, verbose_name='站点源URL')
    search_link = models.CharField(max_length=200, verbose_name='查询URL')
    search_keyword = models.CharField(max_length=20, verbose_name='查询参数')
    # 查询结果页面解析配置
    novel_link = models.CharField(max_length=200, verbose_name='小说主页地址')
    novel_name = models.CharField(max_length=100, verbose_name='书名')

    # 小说主页信息获取
    title = models.CharField(max_length=100, verbose_name='主页书名')
    description = models.CharField(max_length=200, verbose_name='主页简介')
    image = models.CharField(max_length=200, verbose_name='封面图片')
    category = models.CharField(max_length=200, verbose_name='分类')
    author = models.CharField(max_length=200, verbose_name='作者')
    status = models.CharField(max_length=200, verbose_name='更新状态')
    update = models.CharField(max_length=200, verbose_name='最后更新时间')
    latest = models.CharField(max_length=200, verbose_name='最近章节')

    # 章节信息
    chapter_list = models.CharField(max_length=200, verbose_name='章节列表')
    chapter_name = models.CharField(max_length=200, verbose_name='章节名称')
    chapter_link = models.CharField(max_length=200, verbose_name='章节地址')
    text = models.CharField(max_length=200, verbose_name='章节正文')

    # priority 优先级
    priority = models.IntegerField(verbose_name='查询优先级', default=1)

    class Meta:
        verbose_name = '源站点配置'
        verbose_name_plural = '源站点配置'

    def __str__(self):
        return self.site_desc


class BookTag(models.Model):
    tag_name = models.CharField(
        max_length=50, verbose_name='书本分类', unique=True)

    class Meta:
        verbose_name = '书本分类'
        verbose_name_plural = '书本分类'

    def __str__(self):
        return self.tag_name

    @property
    def countTagBooks(self):
        return Book.objects.filter(tag=self.id).count()


class Book(models.Model):
    name = models.CharField(max_length=100, verbose_name='书名')
    tag = models.ForeignKey(BookTag, blank=True, null=True)
    source_site = models.CharField(max_length=100, verbose_name='来源网站')
    source_site2 = models.ForeignKey(
        Config, verbose_name='站点源', default='', null=True, blank=True)
    author = models.CharField(
        max_length=50, verbose_name='作者', default='暂无作者信息')
    img = models.CharField(max_length=200, verbose_name='封面地址', default='')
    desc = models.CharField(max_length=1000, verbose_name='简介', default='')
    index_url = models.CharField(
        max_length=200, verbose_name='主页', blank=True, null=True)
    down_url = models.CharField(
        max_length=200, verbose_name='下载地址', blank=True, null=True, default='')

    add_time = models.DateTimeField(verbose_name='入库时间', auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='更新时间', auto_now=True)

    hot = models.IntegerField(verbose_name='火热指数', default=0)
    read_on_site = models.BooleanField(verbose_name='本站是否可读', default=False)

    read_times = models.IntegerField(verbose_name='阅读次数', default=1)
    download_times = models.IntegerField(verbose_name='下载次数', default=1)

    class Meta:
        verbose_name = '小说'
        verbose_name_plural = '小说'

    def __str__(self):
        return self.name

    @property
    def get_default_source(self):
        try:
            site = Config.objects.get(site_short_name=self.source_site)
            return site.id
        except:
            return None


class BookChapter(models.Model):
    book = models.ForeignKey(Book)
    title = models.CharField(max_length=100, verbose_name='章节名称')
    url = models.CharField(max_length=200, verbose_name='章节地址')
    index = models.IntegerField(verbose_name='章节序号')
    path = models.CharField(max_length=100, verbose_name='内容路径', default='')

    class Meta:
        ordering = ['-index']
        verbose_name = '小说章节'
        verbose_name_plural = '小说章节'

    def __str__(self):
        return self.title


class Feedback(models.Model):
    title = models.CharField(max_length=100, verbose_name='问题')
    desc = models.CharField(max_length=500, verbose_name='详细描述')
    email = models.EmailField(
        max_length=50, verbose_name='邮箱', null=True, blank=True)

    add_time = models.DateTimeField(verbose_name='反馈时间', auto_now_add=True)

    done_flag = models.BooleanField(verbose_name='是否解决', default=False)

    class Meta:
        verbose_name = '问题反馈'
        verbose_name_plural = '问题反馈'

    def __str__(self):
        return self.title


class FeedbackComment(models.Model):
    feedback = models.ForeignKey(Feedback, verbose_name='所属问题')
    parent_comment = models.ForeignKey(
        'self', related_name='my_children', blank=True, null=True)
    comment = models.CharField(max_length=200, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name='回复人', null=True, blank=True)

    def clean(self):
        if len(self.comment) == 0:
            raise ValidationError('评论内容不能为空')

    def __str__(self):
        return self.comment

novel/views.py
# coding : utf8
import logging
import json
import time

from django.http import HttpResponse, StreamingHttpResponse, HttpResponseBadRequest
from django.template import RequestContext, Context
from django.template.loader import get_template
from django.shortcuts import render_to_response, redirect
from django.utils.http import urlquote
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from .models import Book, BookChapter, Feedback
# from .parse_novels import search as book_search, get_hot_books_by_json, search_like_bookname
# from .parse_novels import record_books, get_hot_number
from .fetch_novel import save_content, get_chapter_content, escape
from .fetch import search_by_config


def get_html(template_filename, context):
    this_context = context
    t = get_template(template_filename)
    content_html = t.render(Context(this_context))
    payload = {
        'content_html': content_html,
        'success': True
    }
    return HttpResponse(json.dumps(payload), content_type="application/json")


def index(request):
    # hot_books = get_hot_books_by_json()[:24]
    hot_books = Book.objects.all().order_by('-hot')[:20]
    mycontext = {}
    mycontext.update({'books': hot_books})
    return render_to_response('novel/index.html', context=mycontext, context_instance=RequestContext(request))


def search(request):
    start = time.time()
    mycontext = {}
    if 'bookname' in request.GET and request.GET['bookname']:
        bookname = request.GET['bookname'].strip()
        mycontext.update({'bookname': bookname})
        logging.info('查询: {0}'.format(bookname))
        if not Book.objects.filter(name=bookname).exists():
            # if not this book in, then search from the internet
            search_by_config(bookname)
        if Book.objects.filter(name=bookname).exists():
            books = Book.objects.filter(name=bookname)
        else:
            books = Book.objects.filter(
                name__contains=bookname).order_by('-hot')[:4]
        mycontext.update({'books': books})
        hotbooks = Book.objects.all().order_by('-hot')[:8]
        mycontext.update({'hotbooks': hotbooks})
    end = time.time()
    logging.info('查询耗时: {0}'.format(end - start))
    return render_to_response('novel/search.html', context=mycontext, context_instance=RequestContext(request))


@csrf_exempt
def book_index(request, book_id):

    book = Book.objects.get(pk=book_id)
    chapters = BookChapter.objects.filter(book=book).order_by('index')
    paginator = Paginator(chapters, 144)
    page_count = paginator.num_pages
    page_range = paginator.page_range

    # ajax 分页请求处理
    if request.method == 'POST' and request.is_ajax():
        current_page = int(request.POST.get('current_page')) + 1
        chapters = paginator.page(current_page)
        return get_html('novel/chapters.html', locals())

    chapters = paginator.page(1)
    book.read_times += 1
    book.save()
    return render_to_response('novel/bookindex.html', locals())


def chapter(request, book_id, index):
    mycontext = {}
    try:
        book = Book.objects.get(pk=book_id)
        chapter_count = BookChapter.objects.filter(book=book).count()
        chapter = BookChapter.objects.filter(
            book=book).filter(index=index).first()
        source_site = book.source_site
        title = chapter.title
        url = chapter.url
        content = get_chapter_content(url, source_site)
        content = escape(content)
        # content
        # content = escape(content)
        mycontext.update({'book_id': book.pk})
        mycontext.update({'bookname': book.name})
        mycontext.update({'title': title})
        mycontext.update({'content': content})
        if int(index) > 0:
            mycontext.update({'previous_': str(int(index) - 1)})
        if int(index) < chapter_count - 1:
            mycontext.update({'next_': int(index) + 1})

        return render_to_response('novel/chapter.html', context=mycontext)
    except Book.DoesNotExist:
        return redirect('novel:index')
    except Exception as e:
        mycontext.update({'error': 'fetch content error, please reclick..'})
        logging.error(e)
        return redirect('novel:book', book_id)


def update(request, book_id):
    try:
        book = Book.objects.get(pk=book_id)
        noveldata = {}
        noveldata.update({'id': book.source_site})
        noveldata.update({'content_link': book.index_url})
        chapters = save_content(noveldata=noveldata)
        for index, chapter in enumerate(chapters):
            chapter_title, url = chapter
            bookchapter = None
            if BookChapter.objects.filter(book=book).filter(index=index).exists():
                pass
            else:
                bookchapter = BookChapter(
                    book=book, title=chapter_title, url=url, index=index)
                bookchapter.save()
    except Book.DoesNotExist:
        logging.error('book does not exist')
    except Exception as e:
        logging.error('fetch book chapters error...')
        logging.error('{0}'.format(e))
    return redirect('novel:book', book_id=book_id)


def download(request, book_id):
    logging.info('download book: {0} begin'.format(book_id))
    book = Book.objects.get(pk=book_id)
    book.download_times += 1
    book.save()
    file_name = book.name + '.txt'

    def downloadbook():
        chapters = BookChapter.objects.filter(
            book_id=book_id).order_by('index')
        for chapter in chapters:
            title = chapter.title
            content = get_chapter_content(
                chapter_url=chapter.url, book_website=book.source_site)
            yield title + '\n' + content + '\n'

    response = StreamingHttpResponse(downloadbook())
    response['Content-Type'] = 'application/octet-stream'
    response[
        'Content-Disposition'] = 'attachment;filename="{0}"'.format(urlquote(file_name))
    logging.info('download book: {0} end'.format(book_id))
    return response


def page_not_found(request):
    return render_to_response('404.html')


def page_error(request):
    return render_to_response('500.html')


@csrf_exempt
def feedback(request):

    if request.method == 'GET':
        feedbacks = Feedback.objects.all().order_by('-add_time')[:5]
        return render_to_response('novel/feedback.html', locals())
    elif request.method == 'POST':
        title = request.POST.get('title')
        desc = request.POST.get('desc')
        email = request.POST.get('email')
        fb = Feedback(title=title, desc=desc, email=email)
        fb.save()
        return redirect('novel:feedback')
    else:
        return HttpResponseBadRequest('非法访问方式.')

templates/novel/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "/static/materialize/css/materialize.css" %}">
    {% block cssfiles %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% endblock cssfiles %}
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>{% block title %}
      小说下载-热门小说
    {% endblock title %}</title>
</head>
<main></main>
<body>
    {% block topnav %}
    <nav>
        <div class="nav-wrapper green lighten-1">
            <a href="{% url "novel:index" %}" class="brand-logo center">热门小说</a>
            {# <a href="{% url "novel:search" %}" class="brand"><i class="mdi-action-search"></i></a> #}
            <ul id="nav-mobile" class="right">
                <li><a href="{% url "novel:feedback" %}">反馈</a></li>
            </ul>
            <ul id="nav-mobile" class="left">
                <li><a href="{% url "novel:index" %}">首页</a></li>
            </ul>
        </div>
    </nav>
    {% endblock topnav %}
    {% block bottom-btn %}
        <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
            <a href="{% url "novel:feedback" %}" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">edit</i></a>
        </div>
    {% endblock bottom-btn %}
    {% block content %}
    {% endblock content %}
    {% block footer %}
    <footer class="page-footer green lighten-1">
        {# <div class="footer-copyright"> #}
            <div class="container">
                <div class="row">
                    <div class="col s12 m6 l6"><p class="center">提供小说下载服务,内容来源网络,请勿商用</p></div>
                    <div class="col s12 m6 l6"><p class="center">小说下载网 © 2016 Copyright 韵淡烽青</p></div>
                </div>
            </div>
        {# </div> #}
    </footer> 
    {% endblock footer %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static "/static/materialize/js/materialize.min.js" %}"></script>
    <style type="text/css">
        html, body {
            background-image: url("{% static "/static/images/background.png" %}");
        }
    </style>
    {% block javascript %}
         
    {% endblock javascript %}
    {% block cnzz %}
    <div style="display:none">
        <script type="text/javascript">
        var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
        document.write(unescape("%3Cspan id='cnzz_stat_icon_1260407246'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1260407246' type='text/javascript'%3E%3C/script%3E"));
        </script>
    </div>
    {% endblock cnzz %}
</body>
</html>

templates/novel/bookindex.html
{% extends "novel/base.html" %}
{% block title %}
    小说下载-{{ book.name }}
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m6 l6">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ book.img }}" height="250" width="200" alt="">
                    </div>
                    <div class="card-content">
                        <div class="col s6">
                            <p>{{ book.name }}</p>
                        </div>
                        <div class="col s6">
                            <span>{{ book.author }}</span>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="col s6">
                            <span>阅读次数:{{ book.read_times }}</span>
                        </div>
                        <div class="col s6">
                            <span>下载次数{{ book.download_times }}</span>
                        </div>
                    </div>
                    <div class="card-action">
                        
                        {% if book.read_on_site and book.index_url %}
                        <div class="col s6">
                            <a href="{% url "novel:update" book.id %}">更新章节</a>
                        </div>
                        <div class="col s6">
                            <a href="{% url "novel:download" book.id %}">下载</a>    
                        </div>
                        {% else %}
                        <div class="col s12">
                            <p class="red lighten-1">本书暂不能阅读/下载...</p>
                        </div>
                            
                        {% endif %}
                        <div class="col s12">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s12 m6 l6">
                <div class="row">
                    <div class="col s12">
                         <h3>{{ book.name }}</h3>
                         <p class="flow-text">{{ book.desc }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" id="chapters">
            {% block chapters %}
                {% include "novel/chapters.html" %}
            {% endblock chapters %}
        </div>

        <div class="row">
            <div class="col s12 m6 l6">
                <ul class="pagination">
                    <li class="disabled"><a href="#">&laquo;</a></li>
                    {% for page_num in page_range  %}
                        <li class="waves-effect"><a class="page" href="#">{{page_num}}</a></li>
                    {% endfor %}
                    <li class="waves-effect"><a href="#!">&raquo;</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}

<script type="text/javascript">
//---------------------当前导航项高亮--------------------------
/*$(function(){
    var category="{{category}}";
    $('.'+category).addClass('active');
})*/
//-----------------------------------------------------------------------
//---------------------异步加载当前文章条目----------------------------------------------------------------------------------------------------
    $(function(){
        var current_page=1;
        var a=$("ul.pagination>li>.page");
        var pages={{ page_count }};//总页数,注意从0开始计
        var url = window.location.href;
        console.log(url);
        var color_o=a.css('color');
        a[0].style.color="red";
        current_page=0;
        //上一页click事件
        $("ul.pagination>li>a:first").click(function(event) {
            a[current_page].style.color=color_o;
            current_page-=1;
            //console.log(current_page);
            if(current_page<0){
                current_page=0;
            }else{
                //url=base_url.toString()+current_page;
                //window.location.replace(url);
            }
            a[current_page].style.color='red';
            get_data(current_page,url);
            console.log('current_page is '+current_page);
        });
        //下一页click事件        
        $("ul.pagination>li>a:last").click(function(event) {
            a[current_page].style.color=color_o;
            current_page+=1;
            //console.log(current_page);
            if(current_page>pages-1){
                current_page=pages-1;
            }else{
                //url=base_url.toString()+current_page;
                //window.location.replace(url);
            }
            a[current_page].style.color='red';
            get_data(current_page,url);
            console.log('current_page'+current_page);
        });
        
        //为每一个页面标签绑定click事件
        a.each(function(index, el) {
            $(this).click(function(event) {
                //console.log(index);
                if(index<=pages-1){
                    a[current_page].style.color=color_o;            
                    current_page=index;
                    console.log('index:'+index);
                    a[current_page].style.color='red';
                    get_data(current_page,url);
                    }else{
                        alert("没有该页数据！")
                    }

                });
        });
        $("ul.pagination>li>.page").addClass(function(index, currentClass) {
            console.log("index?"+index);
            if (index == current_page) {
                $("a").addClass('active');
                $("a").removeClass('waves-effect');
            } else {
                $("a").removeClass('active');
                $("a").addClass('waves-effect');
            }
        });
    })
    function get_data(current_page,url){
     $.ajax({
                type: "POST",
                data: {current_page:current_page,},
                url: url,
                cache: false,
                dataType: "json",
                success: function(data) {
                        //var dat=jQuery.parseJSON(data);
                        //$('.posts').children().remove();
                        //$('.posts').html(dat[0].fields.content);
                        //console.log(dat[0].fields.content);
                        console.log('remove begin');
                        $('#chapters').children().remove();//
                        console.log('remove end');
                        $('#chapters').html(data.content_html);
                        console.log('write end');
            },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                console.log('error');
            }
        })
    }
</script>
{% endblock javascript %}

templates/novel/chapter.html
{% extends "novel/base.html" %}
{% block title %}
小说下载网-{{bookname}}-{{ title }}
{% endblock title %}
{% block bottom-btn %}
    
{% endblock bottom-btn %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s10 offset-s1">
                <h3 class="center-align"><a href="{% url "novel:book" book_id %}">{{ bookname }}</a></h3>
            </div>
        </div>
        <div class="row">
            <div class="col s10 offset-s1">
                <h4 class="center-align">{{ title }}</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                {% autoescape off %}
                <p class="flow-text" id="content">{{ content }}</p>
                {% endautoescape %}
            </div>
        </div>
        <div class="row">
            <div class="col s12">
            {% if previous_ %}
                <div class="left"><a href="{% url "novel:chapter" book_id previous_ %}">上一章</a></div>
            {% endif %}
            {% if next_ %}
                <div class="right"><a href="{% url "novel:chapter" book_id next_ %}">下一章</a></div>
            {% endif %}
            </div>    
        </div>
    </div>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript">
        function setFontSize()
        {
        document.getElementById("content").style.fontSize="larger";
        };
    </script>
{% endblock javascript %}

templates/novel/chapters.html
{% for chapter in chapters %}
    <div class="col s6 m4 l3">
        <p><a style="color: black" href="{% url "novel:chapter" book.id chapter.index %}">{{ chapter.title }}</a></p>
    </div>
{% endfor %}

templates/novel/index.html
{% extends "novel/base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <form action="{% url "novel:search" %}" method="get" class="col s12">
                <div class="row">
                    <div class="input-field col s6">
                        <input id="bookname" name="bookname" type="text" placeholder="输入小说全名" />
                    </div>
                    <div class="col s6">
                         <button class="btn-floating btn-large waves-effect waves-light red" type="submit">
                         <i class="material-icons">search</i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="row">
            {% for book in books %}
                <div class="col s6 m3 l3">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{book.img}}" height="150" width="100">
                        </div>
                        <div class="card-content">
                            <p>{{book.name}}</p>
                            <p>作者:{{book.author}}</p>
                        </div>
                        <div class="card-action">
                            {% if book.read_on_site and book.index_url %}
                                <a href="{% url "novel:book" book.pk %}">阅读</a>
                                <a href="{% url "novel:download" book.pk %}">下载</a>    
                            {% else %}
                                <p class="red lighten-1">本书暂不能阅读/下载...</p>
                            {% endif %}
                        </div>
                    </div>
                </div>      
            {% endfor %}
                           
        </div>
    </div>
{% endblock content %}

templates/novel/search.html
{% extends "novel/base.html" %}
{% block title %}
小说下载网-{{bookname}}-查询结果
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <form action="{% url "novel:search" %}" method="get" class="col s12">
                <div class="row">
                    <div class="input-field col s6">
                        <input id="bookname" name="bookname" type="text" placeholder="输入小说全名" />
                    </div>
                    <div class="col s6">
                         <button class="btn-floating btn-large waves-effect waves-light red" type="submit">搜
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="row">
        {% if books %}
            <div class="col s12 m6 l6">
            <p style="color: green">小说下载网-{{bookname}}-查询结果</p>
            </div>
        {% endif %}
        </div>
        <div class="row">
        {% for book in books %}
                <div class="col s12 m6 l6 center">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{ book.img }}" height="250" width="200">
                        </div>
                        <div class="card-content">
                            <p>{{ book.name }}</p>
                            <p>作者:{{ book.author }}</p>
                        </div>
                        <div class="card-action">
                            {% if book.read_on_site and book.index_url %}
                                <a href="{% url "novel:book" book.pk %}">阅读</a>
                                <a href="{% url "novel:download" book.pk %}">下载</a>    
                            {% else %}
                                <p class="red lighten-1">本书暂不能阅读/下载...</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col s6 m3 l3">
            {% if not books %}
                <p style="color: red">抱歉，没找到，或许你可以下载热门小说看看</p>
            {% else %}
                <p style="color: red">最近热门</p>
            {% endif %}
            </div>
        </div>
        <div class="row">
            {% for book in hotbooks %}
                <div class="col s6 m3 l3">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{book.img}}" height="150" width="100">
                        </div>
                        <div class="card-content">
                            <p>{{ book.name }}</p>
                            <p>作者:{{ book.author }}</p>
                        </div>
                        <div class="card-action">
                            {% if book.read_on_site and book.index_url %}
                                <a href="{% url "novel:book" book.pk %}">阅读</a>
                                <a href="{% url "novel:download" book.pk %}">下载</a>    
                            {% else %}
                                <p class="red lighten-1">本书暂不能阅读/下载...</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}