newnovel/urls.py
from django.conf.urls import include, url, handler404, handler500
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


handler404 = "novel.views.page_not_found"
handler500 = "novel.views.page_error"

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('novel.urls', namespace='novel', app_name='novel')),
    url(r'^usercenter/', include('usercenter.urls', namespace='usercenter', app_name='usercenter')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

novel/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'novel'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', views.search, name='search'),
    url(r'^book/(?P<book_id>[0-9]+)/$', views.book_index, name='book'),
    url(r'^book/(?P<book_id>[0-9]+)/(?P<index>[0-9]+)/$',
        views.chapter, name='chapter'),
    url(r'^update/(?P<book_id>[0-9]+)/$', views.update, name='update'),
    url(r'^download/(?P<book_id>[0-9]+)/$', views.download, name='download'),
    url(r'^feedback/', views.feedback, name='feedback'),
]

novel/models.py
# coding=utf-8

from django.db import models
from django.conf import settings

# Create your models here.


class Config(models.Model):
    # 站点源信息
    site_short_name = models.CharField(
        max_length=20, verbose_name='ID', unique=True)
    site_desc = models.CharField(max_length=50, verbose_name='站点源')
    site_url = models.CharField(max_length=200, verbose_name='站点源URL')
    search_link = models.CharField(max_length=200, verbose_name='查询URL')
    search_keyword = models.CharField(max_length=20, verbose_name='查询参数')
    # 查询结果页面解析配置
    novel_link = models.CharField(max_length=200, verbose_name='小说主页地址')
    novel_name = models.CharField(max_length=100, verbose_name='书名')

    # 小说主页信息获取
    title = models.CharField(max_length=100, verbose_name='主页书名')
    description = models.CharField(max_length=200, verbose_name='主页简介')
    image = models.CharField(max_length=200, verbose_name='封面图片')
    category = models.CharField(max_length=200, verbose_name='分类')
    author = models.CharField(max_length=200, verbose_name='作者')
    status = models.CharField(max_length=200, verbose_name='更新状态')
    update = models.CharField(max_length=200, verbose_name='最后更新时间')
    latest = models.CharField(max_length=200, verbose_name='最近章节')

    # 章节信息
    chapter_list = models.CharField(max_length=200, verbose_name='章节列表')
    chapter_name = models.CharField(max_length=200, verbose_name='章节名称')
    chapter_link = models.CharField(max_length=200, verbose_name='章节地址')
    text = models.CharField(max_length=200, verbose_name='章节正文')

    # priority 优先级
    priority = models.IntegerField(verbose_name='查询优先级', default=1)

    class Meta:
        verbose_name = '源站点配置'
        verbose_name_plural = '源站点配置'

    def __str__(self):
        return self.site_desc


class BookTag(models.Model):
    tag_name = models.CharField(
        max_length=50, verbose_name='书本分类', unique=True)

    class Meta:
        verbose_name = '书本分类'
        verbose_name_plural = '书本分类'

    def __str__(self):
        return self.tag_name

    @property
    def countTagBooks(self):
        return Book.objects.filter(tag=self.id).count()


class Book(models.Model):
    name = models.CharField(max_length=100, verbose_name='书名')
    tag = models.ForeignKey(BookTag, blank=True, null=True)
    source_site = models.CharField(max_length=100, verbose_name='来源网站')
    source_site2 = models.ForeignKey(
        Config, verbose_name='站点源', default='', null=True, blank=True)
    author = models.CharField(
        max_length=50, verbose_name='作者', default='暂无作者信息')
    img = models.CharField(max_length=200, verbose_name='封面地址', default='')
    desc = models.CharField(max_length=1000, verbose_name='简介', default='')
    index_url = models.CharField(
        max_length=200, verbose_name='主页', blank=True, null=True)
    down_url = models.CharField(
        max_length=200, verbose_name='下载地址', blank=True, null=True, default='')

    add_time = models.DateTimeField(verbose_name='入库时间', auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='更新时间', auto_now=True)

    hot = models.IntegerField(verbose_name='火热指数', default=0)
    read_on_site = models.BooleanField(verbose_name='本站是否可读', default=False)

    read_times = models.IntegerField(verbose_name='阅读次数', default=1)
    download_times = models.IntegerField(verbose_name='下载次数', default=1)

    class Meta:
        verbose_name = '小说'
        verbose_name_plural = '小说'

    def __str__(self):
        return self.name

    @property
    def get_default_source(self):
        try:
            site = Config.objects.get(site_short_name=self.source_site)
            return site.id
        except:
            return None


class BookChapter(models.Model):
    book = models.ForeignKey(Book)
    title = models.CharField(max_length=100, verbose_name='章节名称')
    url = models.CharField(max_length=200, verbose_name='章节地址')
    index = models.IntegerField(verbose_name='章节序号')
    path = models.CharField(max_length=100, verbose_name='内容路径', default='')

    class Meta:
        ordering = ['-index']
        verbose_name = '小说章节'
        verbose_name_plural = '小说章节'

    def __str__(self):
        return self.title


class Feedback(models.Model):
    title = models.CharField(max_length=100, verbose_name='问题')
    desc = models.CharField(max_length=500, verbose_name='详细描述')
    email = models.EmailField(
        max_length=50, verbose_name='邮箱', null=True, blank=True)

    add_time = models.DateTimeField(verbose_name='反馈时间', auto_now_add=True)

    done_flag = models.BooleanField(verbose_name='是否解决', default=False)

    class Meta:
        verbose_name = '问题反馈'
        verbose_name_plural = '问题反馈'

    def __str__(self):
        return self.title


class FeedbackComment(models.Model):
    feedback = models.ForeignKey(Feedback, verbose_name='所属问题')
    parent_comment = models.ForeignKey(
        'self', related_name='my_children', blank=True, null=True)
    comment = models.CharField(max_length=200, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name='回复人', null=True, blank=True)

    def clean(self):
        if len(self.comment) == 0:
            raise ValidationError('评论内容不能为空')

    def __str__(self):
        return self.comment

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "/static/materialize/css/materialize.css" %}">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>{% block title %}
      小说下载
    {% endblock title %}</title>
</head>
<main></main>
<body>
    {% block topnav %}
    <nav>
        <div class="nav-wrapper green lighten-1">
            <a href="{% url "novel:index" %}" class="brand-logo center">热门小说</a>
            {# <a href="{% url "novel:search" %}" class="brand"><i class="mdi-action-search"></i></a> #}
            <ul id="nav-mobile" class="left">
                {# <li> #}
                    {# <a href="{% url "novel:search" %}" class="btn-floating btn-large waves-effect waves-light red"> #}
                    {# 搜 #}
                    {# </a> #}
                {# </li> #}
            </ul>
        </div>
    </nav>
    {% endblock topnav %}
    {% block content %}
    {% endblock content %}
    {% block footer %}
    <footer class="page-footer green lighten-1">
        {# <div class="footer-copyright"> #}
            <div class="container">
                <div class="row">
                    <div class="col s12 m6 l6"><p class="center">提供小说下载服务,内容来源网络,请勿商用</p></div>
                    <div class="col s12 m6 l6"><p class="center">小说下载网 © 2016 Copyright 韵淡烽青</p></div>
                </div>
            </div>
        {# </div> #}
    </footer> 
    {% endblock footer %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static "/static/materialize/js/materialize.min.js" %}"></script>
    <style type="text/css">
        html, body {
            background-image: url("{% static "/static/images/background.png" %}");
        }
    </style>
    {% block javascript %}         
    {% endblock javascript %}
</body>
</html>

templates/register.html
{% extends "base.html" %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col s1 m3 l3">
            &nbsp;
        </div>
        <div class="col s10 m6 l6">
            {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endif %}
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3>注册</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="input-group">
                            <span class="input-group-addon">昵称</span>
                            <input id="id_username" maxlength="254" name="nickname" type="text" class="form-control" />
                        </div>
                        <br />
                        <div class="input-group">
                            <span class="input-group-addon">邮箱&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <input id="id_email" name="email" type="text" class="form-control" />
                        </div>
                        <br />
                        <div class="input-group">
                            <span class="input-group-addon">密码&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <input id="id_password" name="password" type="password" class="form-control" />
                        </div>
                        <br />
                        <div class="input-group">
                            <span class="input-group-addon">确认密码</span>
                            <input id="id_re_password" name="re_password" type="password" class="form-control" />
                        </div>
                        <br />
                        <input type="submit" class="btn btn-primary" value="注册" />
                    </form>
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
        <div class="col s1 m3 l3">
            &nbsp;
        </div>
    </div>
</div>
{% endblock %}

templates/success_hint.html
{% extends "base.html" %} {% block content %}
<div class="col-md-3">
    &nbsp;
</div>
<div class="col-md-6">
    <h2>{{ msg }}</h2>
    <a href="{{ link }}">{{ hint }}</a>
</div>
<div class="col-md-3">
    &nbsp;
</div>
{% endblock %}